### ISSUE TITLE
Intellij Plugin: NPE

### ISSUE THREAD

**Issue by chilicat** [chilicat/JsChilicat#1]
Maybe occourse because a javascript file as been deleted:

Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=net.chilicat.testenv.ui.TestReportTreeModel$Handler$1@1d93bff,notifier=null,catchExceptions=false,when=1293813817556] on sun.awt.windows.WToolkit@4563a
java.lang.NullPointerException
 at java.io.File.<init>(File.java:222)
 at net.chilicat.testenv.model.Module.getScriptName(Module.java:27)
 at net.chilicat.testenv.ui.TestReportTreeModel$Handler.getParent(TestReportTreeModel.java:88)
 at net.chilicat.testenv.ui.TestReportTreeModel$Handler.access$100(TestReportTreeModel.java:67)
 at net.chilicat.testenv.ui.TestReportTreeModel$Handler$1.run(TestReportTreeModel.java:103)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
 at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:627)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:508)
 at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:405)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:369)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by chilicat** [comment]
fixed.
