### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by reyuto** [chilicat/JsChilicat#13]
I got this error while trying to run my tests from the command line.

This is the code which I was trying to run. Before this, I had cloned from git and built the code.

java -jar dist/production/jschilicat.jar -chilicat -coverage -src testing-coverage/src/ -src-test testing-coverage/test/ -libs testing-coverage/lib/ -workingDir testing-coverage/reports/

Exception in thread "main" java.lang.NoClassDefFoundError: org/restlet/Restlet
    at net.chilicat.testenv.Application.execute(Unknown Source)
    at net.chilicat.testenv.Main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.restlet.Restlet
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by chilicat** [comment]
Make sure that all external libraries are in the class path.

It would be easier if you make a distribution package via: ant sf-dist
The directory sf-dist/libs should contain everything needed. 

Note: Currently the "sf-dist" build fails because some expected directories are not present. Just create the directories then it will work.

JsChilicatServer/src/test/resources
JsChilicatServer/src/test/java

**Comment by chilicat** [comment]
Issue closed because it works if external libs are in the classpath. Pushed also a bugfix to fix the sf-dist build.

**Comment by reyuto** [comment]
Thanks a lot for fixing this issue and also for suggesting a workaround. I am working on integrating the coverage tool with ANT, TestNG and then Clover. And your stack made life much easier for me.

thanks.
